### ISSUE TITLE
Save incomplete Survey

### ISSUE THREAD

**Issue by directionsansa** [dactechie/ansa-surveyjs#10]
![Incomplete Survey](https://user-images.githubusercontent.com/73211789/97251680-6d9d1100-185c-11eb-9530-4a4c526f1382.png)

Asks to "Save Incomplete Survey" at the end of the assessment. 

I did this even though I had completed the survey. When loading data for that client it nows shows it as incomplete and I'm not able to go into it to say that it is complete...

SLK: UY9HI010120001

**Comment by dactechie** [comment]
Auto saving implemented - when navigating away from a page  (and if there are changes to be saved)
